### ISSUE TITLE
질문있습니다.

### ISSUE THREAD

**Issue by yuisatomi** [stjeong/XingAPI#1]
안녕하세요?
XingAPI로 트레이딩 프로그램 돌리고있는 개발자입니다.
언어는 C#으로 쓰고 API는 OCX로 돌리고있는데 OCX가 문제가 한 두가지가 아니라 DLL버전으로 
해보고싶은 마음에 서치 하다보니 이렇게 완제품으로 래퍼를 만드신 분이 있으셨네요.
몇가지 질문이 있는데요.
1. DLL버전은 멀티스레드로 돌려도 괜찮은가요? 
-   OCX는 STA 가 아니면 동작을 안하는지라 INVOKE를 
    쓰는대도 t1857(e종목검색)에서 이벤트 응답이 안오는 문제가 있어서(응답이 안오는 특정 상황을 찾기가 힘듬)  
   이게 API단에서 문제가 있는건지  OCX문제인지 스레드 문제 인지 감이 하나도 안오더군요 . 비슷 한사례로  아래 링크내용 보시면  
   C++로 하시는분이 t1857에 MSG가 안오는 문제에 대해서 써놓으셨는데 OCX를 쓰는 제 입장에선 저 부분을 컨트롤 못하니 DLL을 써야하나 하는 상황입니다.
 https://blog.noyecube.com/entry/xingAPIT1857-T1857-e%EC%A2%85%EB%AA%A9%EA%B2%80%EC%83%89%EC%A1%B0%EA%B1%B4%EA%B2%80%EC%83%89

2. 작업하신 것이 API의 모든 TR을 포함한건지 일부TR인지 궁금합니다.

3. 이번질문은 API말고 트레이딩 관련인데  
    (주문 -  주문 접수 - 주문 체결) 주문 과정을보면  주문을 넣고 접수될때 주문번호가 오게 되는되요 
   트레이더 <> 증권사 <> 시장서버   이렇게 중간에 증권사가  껴서  증권사에서 주문번호를 주는것보다 체결이 먼저되서 
    주문 번호없이 체결데이터가 먼저 수신되는 상황이 종종 있습니다.  API문서를 봐도 이럴 수 있다고 나와있는데.
   개발자님은 이 부분을 어떻게 처리를 하고계신지 노하우를 알려 주실 수 있으신가요?

**Comment by yuisatomi** [comment]
아이고 소스를 이제 보는데  API DLL버전을 을 래핑 하신줄 알았는데 OCX이용하는 거였네요 ㅜㅜ  제가 이해한거 맞지요?

**Comment by stjeong** [comment]
네, 맞습니다. ^^ 이곳에 있는 것은 ocx를 기반으로 합니다. 게다가 저는 아직 주문을 넣어본 적도 없는 초짜입니다. ^^; 그래서 딱히 도움드릴 만한 시행착오가 없습니다.
