### ISSUE TITLE
혹시 키움 OpenAPI처럼 64bit로 변환해서 사용가능한지요?

### ISSUE THREAD

**Issue by cyberprophet** [stjeong/XingAPI#2]
32bit 2GB 메모리제한때문에 그러는데 OCX처럼 64bit로 변환해서 사용 가능한지 여쭙고 싶습니다.

**Comment by stjeong** [comment]
ActiveX를 32비트만 제공하기 때문에 불가능합니다. 그나마  /largeaddressaware 옵션을 활용하신다면 64비트 운영체제에서 32비트 프로세스라도 4GB까지는 운영할 수 있습니다. 아래의 글을 참고하세요.

LargeAddressAware 옵션이 적용된 닷넷 32비트 프로세스의 가용 메모리
; https://www.sysnet.pe.kr/2/0/1441

LargeAddressAware 옵션이 적용된 닷넷 32비트 프로세스의 가용 메모리 - 두 번째
; https://www.sysnet.pe.kr/2/0/13294

**Comment by cyberprophet** [comment]
> 감사합니다.

한 가지 더 여쭤보면 키움 OpenAPI는 메모리 IPC통신을 이용해서 64bit에서 작동시킬 수 있는데 OCX만 가능한건지요?

https://github.com/Share-Invest/securities-modules/tree/NET7/OpenAPI.NET

**Comment by stjeong** [comment]
OCX도 결국 COM입니다. 링크해 주신 프로젝트를 보니까, 내부적으로 키움 OCX가 제공하는 인터페이스를 따르는 64비트 OCX를 만들고 32비트 OCX를 (아마도) DLL Surrogate 등의 기법을 이용해 사용하는 것 같습니다.

C# - DLL Surrogate를 이용한 Out-of-process COM 개체 제작
; https://www.sysnet.pe.kr/2/0/12668

위와 같은 식이라면 XingAPI도 마찬가지로 제공할 수 있습니다.

---------------------------

그건 그런데, Share-Invest 제작자에게는 실례되는 말일 수 있겠지만, 저라면 ShareInvest.OpenAPI를 사용하지 않을 것입니다. 왜냐하면, 64비트 OCX에 대한 소스 코드가 오픈돼 있지 않습니다.

금전 거래를 하는 프로그램을 만드는데 있어, 해당 OCX 내에 악성 코드가 심어져 있지 않다고 100% 신뢰할 수 있겠습니까?

**Comment by cyberprophet** [comment]
답변 감사드립니다.

기존에는 증권사API와 제가 필요한 64bit프로그램을 나누어 제작하고 PipeStream으로 연결해서 사용했었는데 하나로 합치면 편할거 같아서 여쭤봤습니다.
